In [27]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix,recall_score
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('datasets/IRIS_DATASET.csv')

In [21]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
x = df.drop('species', axis=1)

In [6]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [7]:
y = df['species']

In [8]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [9]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 9)

In [11]:
gnb = GaussianNB()

In [23]:
gnb.fit(x_train, y_train)

GaussianNB()

In [17]:
x_test.head()

sepal_length  sepal_width  petal_length  petal_width
135           7.7          3.0           6.1          2.3
90            5.5          2.6           4.4          1.2
145           6.7          3.0           5.2          2.3
147           6.5          3.0           5.2          2.0
60            5.0          2.0           3.5          1.0

In [13]:
y_pred = gnb.predict(x_test)

In [29]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
confusion = confusion_matrix(y_test, y_pred)
recall = recall_score(y_test, y_pred, average=None)
print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Confusion Matrix: \n{confusion}')
print(f'Recall score: {recall}')

Accuracy: 1.0
Precision: [1. 1. 1.]
Confusion Matrix: 
[[13  0  0]
 [ 0  9  0]
 [ 0  0  8]]
Recall score: [1. 1. 1.]


In [26]:
x_test1 = np.array([[5.0, 3.5, 1.5, 0.2]])
y_pred1 = gnb.predict(x_test1)
print(f'classification is: {y_pred1}')

classification is: ['setosa']


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
